# -*- coding: utf-8 -*-
"""python_dictionaries.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZHu_tyMOOjhEfhuaG6_EcotSv5i4g2_

#Exercise 2
"""

def decimal_to_binary(numbers):
  binaryDict = {}
  for number in range(numbers+1):
    curr_num = number
    binaryString = ""

    while curr_num > 0:
     remainder = curr_num%2
     curr_num = curr_num//2
     binaryString = str(remainder)+binaryString

    if len(binaryString) < 4:
      zeros = 4 - len(binaryString)
      for i in range(zeros):
        binaryString = "0" + binaryString

    binaryDict[number] = binaryString

  return binaryDict

decimal_to_binary(15)