# -*- coding: utf-8 -*-
"""data-imputation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JIpNtBVbzKPdPsUf5TsUWcezE6f1Xolc
"""

import pandas as pd
import numpy as  np
import matplotlib.pyplot as plt

#QUIZ

#Question 1: Why is it important to handle null values in datasets?

#Null values or missing data can break function or calculations performed on a data set. Most ML algorithms cannot handle missing data. Missing data can reduce predictive power of a model. Missing data can add bias.

#Questions 1: Read titanic.csv into memory.

df = pd.read_csv("/content/titanic.csv")

df.info()

#Question 2 Impute the missing values in "Age" using the median age of all passengers and store the result in a column called "Age_med".

df['Age_med'] = df['Age'].fillna(df.Age.median())

df.Age_med.isnull().sum()

#Questions 3 Impute the missing values in "Age" using the mean age of passengers of the same sex and store the result in a column called "Age_mean_sex".

df['Age_mean_sex'] = df.groupby('Sex', group_keys=False)['Age'].apply(lambda x: x.fillna(x.mean()))

df.Age_mean_sex.isnull().sum()

df.info()

df.Cabin.value_counts()

df['Cabin'] = df['Cabin'].apply(lambda x: df[df.Cabin.notnull()]['Cabin'].sample().values[0] if x != x else x)

plt.bar(df['Cabin'].value_counts().index, df['Cabin'].value_counts().values)

df.info()

df.Cabin.isnull().sum()

df.info()

df.drop("Cabin_Class_Mode", axis=1, inplace=True)

#Explain why you chose the method you used.

#initially I used the random sample method but removed null values from the sample pool. This scewed the data because the random sampler had greater odds of selecting a cabin type that appears more in the given sample.

#I then assigned cabin type by grouping to class. This again scewed the data in a similar way to random sampling since

#I did not want to label null values in cabin as unknown because I do not think it would be helpful.