# -*- coding: utf-8 -*-
"""is_anagram.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aG_8OCBKK0Fpt3R_M12mtkvsnO-cYU5G

#Exercise 4
"""

def is_anagram(str_1,str_2):
  if len(str_1) != len(str_2):
    return False

  count1 = 0
  count2 = 0

  str1_dict = {}
  str2_dict = {}

  for char in str_1:
    for char1 in str_1:
      if char == char1:
        count1 +=1
    str1_dict[char]=count1
    count1 = 0
  print(str1_dict)

  for char in str_2:
    for char1 in str_2:
      if char == char1:
        count2 +=1
    str2_dict[char]=count2
    count2 = 0
  print(str2_dict)

  for key in str1_dict.keys():
    if not(key in str2_dict):
      return False
    elif str1_dict[key] != str2_dict[key]:
      return False
  return True

text1 = "cat"
text2 = "rat"

is_anagram(text1,text2)