# -*- coding: utf-8 -*-
"""letters_to_symbols.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVH4cKQI-Q_bYc6WbBNvd9OGcX93FjAu

#Exercise 5
"""

def letters_to_symbols(text):
  if len(text) == 0:
    return
  symbol_text = ""
  current_char = text[0]
  counter = 0

  for index in range(len(text)):
    if current_char == text[index]:
      counter += 1
      if(index == len(text)-1):
        symbol_text = symbol_text+str(counter)+current_char
    else:
      symbol_text = symbol_text+str(counter)+current_char
      current_char = text[index]
      counter = 1

  return symbol_text

s="AAAABBBCCDAAA"

letters_to_symbols(s)