# -*- coding: utf-8 -*-
"""reading_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OaGq-CyLwgprPpDYsYki35pcUtiy20Kd
"""

import pandas as pd

"""#Car file"""

cars_df = pd.read_csv("/content/mtcars.csv")

cars_df.to_csv("my_cars.csv",index=False)

my_cars_df = pd.read_csv("my_cars.csv")

cars_df.equals(my_cars_df)

"""#U data file"""

u_df = pd.read_csv("/content/u.data",sep = "\t", header=None)



u_df

u_df.to_csv("my_u.data", index=False, header=None)



my_u_df = pd.read_csv("my_u.data",header=None)

my_u_df

u_df.equals(my_u_df)

"""#Beer File"""

beer_df = pd.read_csv("/content/beer.txt", header=0, sep=' ')

beer_df

beer_df.to_csv("my_beer.csv",index=False)

my_beer_df = pd.read_csv("my_beer.csv")

my_beer_df

beer_df.equals(my_beer_df)

"""#U item"""

item_df = pd.read_csv("/content/u.item",sep='|',encoding="ISO-8859-1",header=None)

item_df

item_df.to_csv("my_u_item.item",index=False,header=False)

my_item_df = pd.read_csv("my_u_item.item",header=None)

my_item_df

my_item_df.equals(item_df)

item_df.info()

my_item_df.info()

"""#NHL"""

NHL_df = pd.read_excel("/content/NHL 2015-16.xlsx")

NHL_df

NHL_df.to_excel("my_NHL 2015-16.xlsx",index=False)

my_NHL_dataframe = pd.read_excel("my_NHL 2015-16.xlsx")

my_NHL_dataframe

NHL_df.equals(my_NHL_dataframe)

"""#File Reading function"""

def reading_data(path):
  extension = ""
  for index in range(len(path)-1,0, -1):
    if(path[index] != "."):
      extension=path[index]+extension
    else:
      break
  if(extension == "csv"):
    return pd.read_csv(path)
  elif(extension== "data"):
    return pd.read_csv(path,sep = "\t", header=None)
  elif(extension == "txt"):
    return pd.read_csv(path, header=0, sep=' ')
  elif(extension == "item"):
    return pd.read_csv(path,header=None)
  elif(extension == "xlsx"):
    return pd.read_excel(path)
  else:
    print("invalid file type")

string = "/content/NHL 2015-16.xlsx"

print(reading_data(string))