# -*- coding: utf-8 -*-
"""visualization-project-laptop-sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PjJHVqauhHbRPFK7HyT3EJIKPWtX2OS
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/Sales_data.txt")

df

df.info()

#Question 1: What is target market? Male or female?
#The mean profit from females are 148.38
#while the mean profit for males is 133.47

df.groupby('Contact Sex')['Profit'].mean()

df.groupby('Contact Sex')['Profit'].mean().plot(kind='bar')

#Question 2: If business is cash-constrained, which gender should be targeted?
#The mean cost from females is $751.84
#while the mean cost for males is $623.76


df.groupby('Contact Sex')['Our Cost'].mean()

#Question 3: If consumer is cash-constrained, which gender should be targeted?
#The mean cost from females customers is $17.417647
#while the mean cost for males customers is $17.750000
#It is better to target females because the customer cost(shipping cost)
#is less than males but the difference is lower so any gender should be fine


df.groupby('Contact Sex')['Shipping Cost'].mean().plot(kind='bar')

#Question 4 What is our target age to maximize profit?
#The max of target age should be 54 since they have the max profit(230)
#The hight sale frequency age is 46.
#The age range that should be target should be 35-55

df['Contact Age'].hist(bins=13)
df['Contact Age'].value_counts()

df['Contact Age'].value_counts()

df.groupby('Contact Age')['Profit'].mean().plot(kind='bar')

df.groupby('Contact Age')['Profit'].mean().sort_values().plot(kind='bar')

df.groupby('Contact Age')['Profit'].mean()

df.groupby('Contact Age')['Profit'].mean().sort_values()

#Question 4:Which product should we feature?
#Desktop have a 28% profit margin while laptop and tablet have around a 17%
#profit margin. Desktops should be featured to optimize profit

df.groupby("Product Type")['Profit'].mean()

df.groupby("Product Type")['Profit'].mean()/df.groupby("Product Type")['Our Cost'].mean()

(df.groupby("Product Type")['Profit'].mean()/df.groupby("Product Type")['Our Cost'].mean()).plot(kind='bar')

#Question 6: What lead sources have worked in the past: website, flyer, or email?
#Website brought in the most lead (14)
#Website also produce the most profit: 	1835.71
#Flyer 3 yield the most profit producing single transaction
#Website worked best

df['Lead Source'].value_counts()

df.groupby('Lead Source')['Profit'].sum().plot(kind='bar')

df.groupby('Lead Source')['Profit'].agg(['sum','mean']).plot(kind='bar')

df.groupby('Lead Source')['Profit'].sum()

df.groupby('Lead Source')['Profit'].mean()

#Question 7: When is the best time to do email marketing?
#November has the most EMAIL sales so email market should be used
#November

df[df['Lead Source'] =='Email'].groupby(['Sale Month','Lead Source'])['Lead Source'].count()

df[df['Lead Source'] =='Email'].groupby(['Sale Month','Lead Source'])['Lead Source'].count().plot(kind="bar")

