# -*- coding: utf-8 -*-
"""telecom_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13dFcQeeUFPLTzyFnBZk7ARa3meVWNKZV
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/telecom.db")

#Question 1: Retrieve table names from the database (telecom.db).

tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")

tables.fetchall()

#Question 2: Join all tables in the database on the primary key.
merged_data = conn.execute("""
              SELECT t.id, t.location, t.fault_severity, et.event_type,
		                st.severity_type, rt.resource_type, lf.log_feature, lf.volume
              FROM train t
	                LEFT OUTER JOIN severity_type st
                	ON t.id = st.id
	                LEFT OUTER JOIN resource_type rt
	                on rt.id = t.id
	                LEFT OUTER JOIN log_feature lf
	                on lf.id = t.id
	                LEFT OUTER JOIN event_type et
	                on et.id = t.id
            """).fetchall()

#Question 3: Find unique occurrences of event_type and severity in the table from #2 using an SQL query.
merged_data_grouped = conn.execute("""
              SELECT t.id, t.location, t.fault_severity, et.event_type,
		                st.severity_type, rt.resource_type, lf.log_feature, lf.volume
              FROM train t
	                LEFT OUTER JOIN severity_type st
                	ON t.id = st.id
	                LEFT OUTER JOIN resource_type rt
	                on rt.id = t.id
	                LEFT OUTER JOIN log_feature lf
	                on lf.id = t.id
	                LEFT OUTER JOIN event_type et
	                on et.id = t.id
                  GROUP BY event_type, severity_type
            """).fetchall()

group_df = pd.DataFrame(merged_data_grouped)

#Question 4: Find how many occurrences there are of each fault_severity in the table from #2 using an SQL query.

fault_severity_count_grouped = conn.execute("""
              SELECT  t.fault_severity, count(*) as occurences
              FROM train t
	                LEFT OUTER JOIN severity_type st
                	ON t.id = st.id
	                LEFT OUTER JOIN resource_type rt
	                on rt.id = t.id
	                LEFT OUTER JOIN log_feature lf
	                on lf.id = t.id
	                LEFT OUTER JOIN event_type et
	                on et.id = t.id
                  GROUP BY fault_severity
            """).fetchall()