# -*- coding: utf-8 -*-
"""custom_datetimes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XVTjAdKoqd8NwW4raWnhZUmH29usG05V
"""

import datetime as dt
import pytz

string1 = "03/23/21"
string2 = "23/03/2021"
string3 = "March 23rd, 2021 13:01 US/Pacific"
string4 = "1:01pm 23rd March, 2021 Europe/London"
string5 = "1616482800"
string6 = "2021-03-23T12:00:53.034-07:00"

dt.datetime.strptime(string1, "%m/%d/%y")

dt.datetime.strptime(string2, "%d/%m/%Y")

tz_var = "US/Pacific"
tz = pytz.timezone(tz_var)
dt.datetime.strptime(string3, "%B %drd, %Y %H:%M US/Pacific").astimezone(tz)

london = pytz.timezone("Europe/London")

dt.datetime.strptime(string4, "%I:%M%p %drd %B, %Y Europe/London").astimezone(london)

string5 = int("1616482800")
dt.datetime.fromtimestamp(string5)

dt.datetime.strptime(string6,"%Y-%m-%dT%H:%M:%S.%f%z")