# -*- coding: utf-8 -*-
"""human_resource_db.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SiV81gTvhXlqRBKwN7yQDij8gjgRvOin
"""

import sqlite3
import pandas as pd

conn = sqlite3.connect("/content/hr.db")

tables = conn.execute("SELECT name FROM sqlite_master WHERE type='table'")

tables.fetchall()

data = conn.execute("""
              SELECT EmployeeNumber, Department, Age, Gender, Attrition
              FROM employee
              WHERE Department = "Sales"
            """).fetchall()

conn.execute("""
              SELECT DISTINCT(EducationField)
              FROM employee
            """).fetchall()

sales_col = ["EmployeeNumber", "Department", "Age", "Gender", "Attrition"]

sales = pd.DataFrame(data, columns = sales_col)
sales

data1 = conn.execute("""
              SELECT EmployeeNumber, EducationField, Age, Gender, Attrition
              FROM employee
              WHERE EducationField = "Life Sciences"
            """).fetchall()

field_col = ["EmployeeNumber", "EducationField", "Age", "Gender", "Attrition"]

field = pd.DataFrame(data1, columns = field_col)
field

conn.execute("CREATE TABLE sales(EmployeeNumber, Department, Age, Gender, Attrition)")

conn.executemany("INSERT INTO sales VALUES(?,?,?,?,?)",data)

conn.execute("CREATE TABLE field(EmployeeNumber, EducationField, Age, Gender, Attrition)")

conn.executemany("INSERT INTO field VALUES(?,?,?,?,?)",data1)

data3 = conn.execute("""
              SELECT *
              FROM sales s
              JOIN field f
              ON s.EmployeeNumber = f.EmployeeNumber
            """).fetchall()

merged_df = pd.DataFrame(data3)

merged_df