# -*- coding: utf-8 -*-
"""birthday.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oVpb7Vu_SWrZRgLPR6pDk3GqBBBGPPyW
"""

import datetime as dt

def birthday(dob):
  birthdate = dt.datetime.strptime(dob,"%m/%d/%Y")
  today = dt.datetime.today()
  delta = today - date
  return delta.days/365

string = "01/13/1997"
print("Your age is: "+ str(birthday(string)))