# -*- coding: utf-8 -*-
"""Python_list_and_tuples.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hw2gAJE920jr28xBdAsXT8A0n8758k4x

#Python Lists and tuples

Exercise 1
"""

List = 'abcdefghijklmnopqrstuvwxyz'

#Function takes in a string and creates a list of tuples for each
#character with their index(index, char) Resubmitting
def list_to_tuples(text):
  array_tuples = []
  for index in range(len(text)):
    array_tuples.append((index+1, text[index]))
  return array_tuples

print(list_to_tuples(List))