# -*- coding: utf-8 -*-
"""tmdb_api.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fpN0EDHx-12EA6HKJ02_a9xDOZZXodrH
"""

import json
import requests
import pandas as pd

movie_api_key = "f060410f5ddf36cee5849df7dcba1343"
url = f"https://api.themoviedb.org/3/search/movie?api_key={movie_api_key}&query=Star+Wars&page=1"

data = requests.get(url)
data
data_obj = json.loads(data.text)
results = data_obj['results']
total_pages = data_obj['total_pages']
type(results)
movie_title_list = []


for i in range(1, total_pages+1):

  url = f"https://api.themoviedb.org/3/search/movie?api_key={movie_api_key}&query=Star+Wars&page={i}"

  data = requests.get(url)
  data_obj = json.loads(data.text)
  results = data_obj['results']


  for item in results:
    movie_title_list.append(item)



df = pd.DataFrame(movie_title_list)

df.sort_values('popularity')