# -*- coding: utf-8 -*-
"""time-series-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wczi7r3TZEd0djSbfc4F_X8XZL4JAeHG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/AirPassengers.csv")

df

df.info()

df.describe()

#converting month column date object
df['Month'] = pd.to_datetime(df['Month'])

df.info()

df

#set data as index
df.set_index('Month', inplace=True)

df.plot()

#data has a positive trend. And high variance with seasonality trend
rolling_7 = df.rolling(7).mean()
df['rolling_7'] = rolling_7

df.plot()

#getting the rolling standard deviation
rolling_7_std = df['#Passengers'].rolling(7).std()
df['rolling_7_std'] = rolling_7_std

df

df.plot()

#1. Exercise 1: the rolling mean is increasing over time due to positive trend.
#There is also high variance in the data.

#2. Exercise 2: Try different level of difference and plot the time series data with rolling mean and standard deviation

df['diff1_new'] = df['#Passengers'].diff(1)
df['diff2_new'] = df['#Passengers'].diff(2)
df['diff3_new'] = df['#Passengers'].diff(3)

df.plot()

#getting the difference standarized mean between the "Horizontal" axis

#now handle the variance by transforming data

df["log_Passengers"] = np.log(df['#Passengers'])

df

df['log_Passengers'].plot()

#3. Exercise 3. Try to transform the data, and make different levels of differences. See if it is stationary.
#tranforming difference data
df['diff1_log'] = np.log(df['#Passengers']).diff(1)
df['diff2_log'] = np.log(df['#Passengers']).diff(2)
df['diff3_log'] = np.log(df['#Passengers']).diff(3)

df['diff1_log'].plot()

#4. Get the p-value from Augmented Dickey-Fuller test to make the data stationary.

from statsmodels.tsa.stattools import adfuller

adf1_log = adfuller(df['diff1_log'].dropna())
adf1_log

adf2_log = adfuller(df['diff2_log'].dropna())
adf2_log

df['diff2_log'].plot()

adf3_log = adfuller(df['diff3_log'].dropna())
adf3_log

df['diff3_log'].plot()

#Getting the log transformation of diff(2) reached a adfuller P value of less than 0.5 making the data stationary.(-3.1679073752887317,0.021919114564039603,...