# -*- coding: utf-8 -*-
"""Bracket_Matcher.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xkmSrQubXSBOP286JE_vvdYFQC_WT7E3

#Exercise 3
"""

#Traverse the text string in search of
#left and right paranthesis
#if a left paranthesis is found we traverse
#the back of the text to find a right paranthesis


def BracketMatcher(text):
  right_index = len(text)-1
  for left_index in range(len(text)):
    if text[left_index] == ")":
      return False
    if left_index == right_index:
      return True
    if text[left_index] == "(":
      flag = True
      while flag:
        if left_index == right_index or text[right_index] == "(":
          return False
        if text[right_index] != ")":
          right_index -= 1
        else:
          right_index -= 1
          flag = False

s = '(a((kl(mns)t)uvwz)'
print(BracketMatcher(s))