# -*- coding: utf-8 -*-
"""scraping_formula1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1snCqmsYHmw4vqjEfqHKb6tSQz64XqumN
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://www.formula1.com/en/results.html/2022/drivers.html"

r = requests.get(url)
r

if r.status_code == 200:
  print("Ok")
else:
  print("Different status code:" + r.status_code)

content = r.content

soup = BeautifulSoup(r.content)

tables = soup.find_all('table')
len(tables)

data_table = tables[0]

len(data_table)

data_table.find_all('th')

header_data = data_table.find_all('th')

headers = []

for h in header_data:
  headers.append(h.get_text())

len(row_data)

rows = []
for tr in row_data[1:]:
  tds = tr.find_all('td')
  row = [td.get_text() for td in tds]
  rows.append(row)

rows

df = pd.DataFrame(rows, columns=headers)

df

#saving dataframe to csv file
df.to_csv("Scraping_Formula.csv",index=False)
dataframe_csv = pd.read_csv("/content/Scraping_Formula.csv")
dataframe_csv

df_pd = pd.read_html(url)[0]
df_pd

